LAMPSPUC/StateSpaceModels.jl

- docs/make.jl
- docs/src/index.md
- src/StateSpaceModels.jl
- src/estimation.jl
- src/modeling.jl
Took out parallel optimization of seeds in estimation.jl
> Unparallelize

- src/StateSpaceModels.jl
- src/structures.jl
> fixing nseeds inconsistency

- example/missing_observations.jl
- src/estimation.jl
- src/forecast.jl
- src/kalman.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/utils.jl
- test/test_lineartrend.jl
- test/test_results.jl
- test/test_structural.jl
> Missing values in filter and smoother for KalmanFilter

- benchmark/bench.jl
- src/kalman.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/utils.jl
I will do benchmarking on Monday. :)
> fix missing values performance regression

- benchmark/bench.jl
- src/kalman.jl
- src/kalman_utils.jl
Let's improve docs and make a patch release
> minor performance update

- docs/src/manual.md
- src/structures.jl
Fixing some equations that might make people think we allow T, R, H, and Q to vary over time, and some other typos
> minor doc improvements

- docs/src/manual.md
- docs/src/reference.md
- src/StateSpaceModels.jl
- src/estimation.jl
- src/kalman.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/utils.jl
There is still a lot to write hehehe. 
Don't merge this now let's keep discussing some docs
> Some docs updates

- benchmark/bench.jl
- docs/make.jl
- docs/src/manual.md
- src/estimation.jl
- src/kalman.jl
- src/kalman_utils.jl
- src/utils.jl
performance updates and documentation of filter and smoother recursions
> Filter docs

- benchmark/bench.jl
We must start keeping track of structural model benchmarks
> starting to bench structural models

- src/kalman_utils.jl
- src/univariate_kalman.jl
- test/test_lineartrend.jl
- test/test_locallevel.jl
- test/test_results.jl
Don't merge yet, some tests are failing.
Apparently there's a bug in the UnivariateKalmanFilter.
> Adding tests to compare filters

- Project.toml
- README.md
- docs/src/index.md
- docs/src/manual.md
- src/StateSpaceModels.jl
- src/diagnostics.jl
- src/prints.jl
- src/structures.jl
- test/test_lineartrend.jl
- test/test_results.jl
- test/test_structural.jl
> Add diagnostics

- benchmark/bench.jl
- docs/src/manual.md
- src/StateSpaceModels.jl
- src/estimation.jl
- src/forecast.jl
- src/kalman.jl
- src/model_unknowns.jl
- src/random_seeds_lbfgs.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/univariate_kalman.jl
- src/utils.jl
- test/test_lineartrend.jl
- test/test_locallevel.jl
- test/test_results.jl
- test/test_structural.jl
- test/test_utils.jl
Here's a big one, I still need to make some tests to estimate variables in Z and T
> Eliminate StateSpaceCovariance

- docs/src/manual.md
- src/kalman.jl
- src/kalman_utils.jl
- src/model_unknowns.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/univariate_kalman.jl
- src/utils.jl
- test/test_locallevel.jl
This will fix #115 We still ned some nice test
> Added mean adjustments

- .codecov.yml
- .travis.yml
> modify travis

- .travis.yml
- README.md
- src/StateSpaceModels.jl
Some of the packages are in travis-ci.org but it should all be in travis-ci.com
> Update Travis to travis-ci.com

- src/filters/scalar_kalman_filter.jl
- src/fit.jl
- src/hyperparameters.jl
- src/kalman_filter_and_smoother.jl
- src/models/locallevel.jl
- test/models/locallevel.jl
We must consider the refactoring-to-0.4 the base branch until ready to merge with master
> add local level tests

- src/models/common.jl
- src/models/damped_lineartrend.jl
- src/models/lineartrend.jl
Currently the `hasmethod` calls are not doing anything, the function always returns `true`
> Fix has_fit_methods

- Project.toml
- src/systems.jl
- test/models/arima.jl
- test/models/basicstructural.jl
- test/models/locallevel.jl
- test/runtests.jl
- test/utils.jl
Fixed the bug of #176 but I still need to check if the ARIMA model is correct
Closes #176
> Fixed expectation bug for local level and structural model

- Project.toml
- src/kalman.jl
- src/models.jl
- src/sqrt_kalman.jl
- src/structures.jl
- src/univariate_kalman.jl
- src/utils.jl
- test/test_locallevel.jl
- test/test_structural.jl
Addresses #195
This has raised another weird issue where the estimation fails for Float32 series.
Note that this code will be refactored so this is likely to change when 0.4 is merged.
> Fix 32-bit precision

- src/hyperparameters.jl
- src/models/locallevelcycle.jl
See issues in the [manual](https://lampspuc.github.io/StateSpaceModels.jl/latest/manual/)
> Fix some math errors in docs

- Project.toml
this is all I think it takes. Ref #182 #181
> Add Optim v1.2 to compat in Project.toml.

- src/StateSpaceModels.jl
- src/forecast.jl
- src/kalman_filter_and_smoother.jl
- src/models/unobserved_components.jl
- src/optimizers.jl
- test/models/locallevelcycle.jl
- test/models/unobserved_components.jl
- test/runtests.jl
Should we call UnobservedCompoents or Structural? 
Exogenous is still missing.
> Add UnobservedComponents

- src/visualization/forecast.jl
- test/visualization/forecast.jl
This closes #235. It looks like this:
> Add scenarios plots

- Project.toml
- docs/src/examples.md
- docs/src/manual.md
- src/StateSpaceModels.jl
- src/backtest.jl
- src/visualization/backtest.jl
- test/runtests.jl
- test/visualization/backtest.jl
Also, I added a forecasting and simulating section in the manual.md
Closes #239
> Implement a backtest procedure

- Project.toml
- src/kalman_filter_and_smoother.jl
- src/models/common.jl
- src/models/unobserved_components.jl
- src/smoothers/kalman_smoother.jl
- src/systems.jl
- test/models/locallevelexplanatory.jl
> fix kalman smoother for local level explanatory

- src/StateSpaceModels.jl
- src/canova_hensen.jl
- src/models/sarima.jl
Add canova_hanse.jl file with the canova-hansen test and included the test in the auto arima procedure to calculate the seasonal integration order
The tests are on the way
> Canova hansen test

- Project.toml
> Allow Polynomials v2

- .github/workflows/ci.yml
- Project.toml
- src/fit.jl
- src/models/basicstructural_explanatory.jl
- test/models/basicstructural_explanatory.jl
> Fix Basic Structural Model with Explanatory

- Project.toml
- src/models/basicstructural_explanatory.jl
- test/models/basicstructural_explanatory.jl
- test/runtests.jl
> Fix basic structural with exogenous variables simulation

- Project.toml
- src/kalman_filter_and_smoother.jl
- src/visualization/diagnostics.jl
- test/visualization/diagnostics.jl
> Fix `plotdiagnostics(kf)`

- Project.toml
- src/models/unobserved_components.jl
- test/models/sarima.jl
- test/models/unobserved_components.jl
> fix smooth trend

- .github/workflows/ci.yml
- .github/workflows/doc_cleanup.yml
- .github/workflows/documentation.yml
- Project.toml
- docs/src/examples.md
- docs/src/manual.md
- src/StateSpaceModels.jl
- src/cross_validation.jl
- src/filters/multivariate_kalman_filter.jl
- src/filters/regression_kalman_filter.jl
- src/filters/scalar_kalman_filter.jl
- src/filters/sparse_univariate_kalman_filter.jl
- src/filters/univariate_kalman_filter.jl
- src/fit.jl
- src/hyperparameters.jl
- src/models/common.jl
- src/models/sarima.jl
> Update minor version
